### ISSUE TITLE
How to escape double quote in single quotes at json element.

### ISSUE THREAD

**Issue by nobuoonodera** [dakusui/jq-front#132]
I try to run the following json. But, I got error.  How can I express for getting expectation?

json source
`  
 {
    "k":"eval:string:\"'\\\"'\""
 }
`

expectaion
`
{"k":"'\"'"}
`

**Comment by dakusui** [comment]
To get such an output, correct way to achieve it is as following.

```json
{
  "k": "eval:string:$(echo '\"')"
}
```
